[package]
name = "fht2p"
# alpha<alpha.1<beta<rc
version = "0.9.0-alpha"
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A HTTP Server for Static File written with Rust"
build = "build.rs"
license = "MIT"

[workspace]

[profile.release]
opt-level = 3
lto = true
# debug = true 

[build-dependencies]
askama = "^0.7.0"
rsass = "^0.7.0"
time = "^0.1"


[dependencies.signalfn]
path = "./crates/signalfn"
version = "*"

# [dependencies.hyper-fs]
# # git = "https://github.com/biluohc/hyper-fs"
# version = "0.1.1"
# default-features = false

[dependencies.systemstat]
version = "^0.1.3"
# git = "https://github.com/myfreeweb/systemstat"
# branch = "master"

[dependencies]
rustls = "0.12"
tokio = "0.1"
tokio-io = "0.1"
tokio-fs = "0.1"
tokio-tcp = "0.1"
tokio-rustls = "0.6"
tokio-timer = "0.2"
tokio-threadpool = "0.1"
bytes = "^0.4.5"

http = "0.1"
hyper = "0.12.5"
mime_guess="^2.0.0-alpha.5"
askama = "^0.7"
url = "^1.6.0"

serde_derive = "^1.0"
lazy_static = "^1.0.0"
futures ="^0.1.17"
serde = "^1.0"
ron = "^0.4"
chrono = "0.4"

num_cpus = "1.0"
clap = "2"
log = "0.4"
fern = { version = "0.5", features = ["colored"] }




