[package]
name = "fht2p"
version = "0.5.0"
authors = ["biluohc <biluohc@outlook.com>"]

[dependencies]
#urlparse="0.73",chrono = "0.2"
urlparse="*"
chrono = "*"
poolite = { git = "https://github.com/biluohc/poolite" }
stderr = { git = "https://github.com/biluohc/stderr", branch = "master", version = "0.2.1"}