[package]
name = "fht2p"
version = "0.6.0"
authors = ["biluohc <biluohc@qq.com>"]
build = "build.rs"

[dependencies]
tini= { git = " https://github.com/pinecrew/tini" }
urlparse="*"
chrono = "*"
ctrlc="*"  

app = { path = "app" }
stderr = { git = "https://github.com/biluohc/stderr", branch = "master", version = "0.6.1"}
poolite = { git = "https://github.com/biluohc/poolite",branch = "master", version = "0.5.1" }
# stderr= { path = "../stderr" }
# poolite = { path ="../poolite" }

