[package]
name = "fht2p"
# alpha<alpha.1<beta<rc
version = "0.9.0-alpha"
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A HTTP Server for Static File written with Rust"
build = "build.rs"
license = "MIT"

[workspace]

[profile.release]
opt-level = 3
lto = true
# debug = true 

[build-dependencies]
askama = "^0.6.2"
rsass = "^0.7.0"
time = "^0.1"


[dependencies.signalfn]
path = "./crates/signalfn"
version = "*"

# [dependencies.hyper-fs]
# # git = "https://github.com/biluohc/hyper-fs"
# version = "0.1.1"
# default-features = false

[dependencies]
mime_guess="^2.0.0-alpha.3"
# futures-cpupool = "^0.1.7"
serde_derive = "^0.9.14"
mxo_env_logger = "^0.1"
lazy_static = "^1.0.0"
futures ="^0.1.17"
serde = "^0.9.14"

hyper = "0.12"
rustls = "0.12"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-rustls = "0.6"
tokio-tcp = "0.1"

bytes = "^0.4.5"
url = "^1.6.0"
askama = "^0.6.2"
chrono = "^0.4"
toml = "^0.3.2"
log = "^0.3.8"
app = "0.6.5"

[dependencies.systemstat]
version = "^0.1.2"
git = "https://github.com/myfreeweb/systemstat"
branch = "master"

