[package]
name = "fht2p"
version = "0.7.0"
authors = ["biluohc <biluohc@qq.com>"]
build = "build.rs"

[profile.dev]      #    cargo build 
opt-level = 0     
debug = true      
panic = 'unwind'

[profile.release]  #    cargo build --release
opt-level = 3      #    cargo build --release -vv
# debug = false
debug = true 
# panic = 'abort'
panic = 'unwind'

[dependencies]
html5 = { path ="util/html5" }
signal_monitor = { path = "util/signal_monitor" }

tini= { git = " https://github.com/pinecrew/tini", branch = "master", version = "^0.2.0" }
urlparse = "^0.7.3"
time = "^0.1"

stderr ="0.7.0" # 要和 poolite 所用的同一个版本，否则loger不能正常工作。
poolite = "0.6.1"
app = "0.5.5"
# stderr = { git = "https://github.com/biluohc/stderr", branch = "master", version = "0.7.0"}
# poolite = { git = "https://github.com/biluohc/poolite",branch = "master", version = "0.6.1" }
# app = { git = "https://github.com/biluohc/app-rs", branch = "master", version = "0.5.5" }
# stderr = { path = "../stderr" }
# poolite = { path ="../poolite" }
# app = { path = "../app" }

