[package]
name = "fht2p"
version = "0.42.0"
authors = ["biluohc <biluohc@outlook.com>"]

[dependencies]
#urlparse="0.73"     URL decode()
urlparse="*"
#chrono = "0.2"   	 Path Modified_Date
chrono = "*"
