[package]
name = "fht2p"
version = "0.5.3"
authors = ["biluohc <biluohc@outlook.com>"]

[dependencies]
rust-ini="*"
urlparse="*"
chrono = "*"
ctrlc="*"  

stderr = { git = "https://github.com/biluohc/stderr", branch = "master", version = "0.3.0"}
poolite = { git = "https://github.com/biluohc/poolite",branch = "master", version = "0.3.0" }
#poolite = { path ="../poolite"}

