[package]
name = "fht2p"
version = "0.8.1"
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A HTTP Server for Static File written with Rust"
build = "build.rs"

[profile.release]
opt-level = 3
# lto = true
# debug = true 

[build-dependencies]
encoding = "^0.2"
chardet = "^0.2"
time = "^0.1"

[dependencies]
mxo_env_logger = "^0.1"
lazy_static = "^0.2.8"
serde_derive = "^0.9.14"
serde = "^0.9.14"
time = "^0.1"
toml = "^0.3.2"
log = "^0.3.8"
app = "0.6.3"
futures-cpupool= "^0.1.7"
tokio-core = "^0.1.10"
futures ="^0.1.17"
walkdir = "^2.0.1"
hyper = "^0.11.8"
bytes = "^0.4.5"
url = "^1.6.0"

hyper-fs = {path="../hyper-fs", version= "*"}

