[package]
name = "fht2p"
version = "0.8.0"
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A HTTP Server for Static File written with Rust"

[[bin]]
doc = false
name = "fht2p"
path = "src/main.rs"

build = "build.rs"

[profile.dev]      #    cargo build 
opt-level = 0     
debug = true      
panic = 'unwind'

[profile.release]  #    cargo build --release
opt-level = 3      #    cargo build --release -vv
# debug = false
# debug = true 
# panic = 'abort'
panic = 'unwind'

[workspace]
[dependencies]
signal_monitor = { path = "util/signal_monitor" }

maud = "^0.16.2"
maud_macros = "^0.16.3"
lazy_static = "^0.2.8"
urlparse = "^0.7.3"
time = "^0.1"
toml = "^0.3.2"
serde_derive = "^0.9.14"
serde = "^0.9.14"

stderr ="0.7.1" # 要和 poolite 所用的同一个版本，否则loger不能正常工作。
poolite = "0.6.2"
app = "0.5.6"

# stderr = { git = "https://github.com/biluohc/stderr", branch = "master", version = "0.7.0"}
# poolite = { git = "https://github.com/biluohc/poolite",branch = "master", version = "0.6.1" }
# app = { git = "https://github.com/biluohc/app-rs", branch = "master", version = "0.5.5" }
# stderr = { path = "../stderr" }
# poolite = { path ="../poolite" }
# app = { path = "../app" }
