[package]
name = "fht2p"
version = "0.9.0-alpha" # alpha<alpha.1<beta<rc
authors = ["Wspsxing <biluohc@qq.com>"]
description = "A HTTP Server for Static File written with Rust"
build = "build.rs"
license = "MIT"

[workspace]

[profile.release]
opt-level = 3
lto = true
# debug = true 

[build-dependencies]
askama = "0.7.1"
rsass = "0.9.2"
time = "0.1"

[dependencies]
rustls = "0.13.1"
tokio = "0.1.8"
tokio-io = "0.1.8"
tokio-fs = "0.1.3"
tokio-rustls = "0.7.2"
tokio-timer = "0.2.6"
tokio-reactor = "0.1.5"
tokio-threadpool = "0.1.6"
bytes = "0.4.10"
net2 = "0.2.33"

http = "0.1.13"
hyper = "0.12.9"
mime_guess = "2.0.0-alpha.6"
askama = "0.7.1"
url = "1.6.0"

serde_derive = "1.0.78"
lazy_static = "1.1.0"
futures = "0.1.22"
serde = "1.0.78"
ron = "0.4"
fern = { version = "0.5.6", features = ["colored"] }
chrono  = { version = "0.4.6", features = ["serde"] }
bytesize = "1.0.0"

num_cpus = "1.0"
clap = "2.32"
log = "0.4.5"
cfg-if = "0.1.5"
failure = "0.1.2"
failure_derive = "0.1.2"
httparse = "1.3.2"
tokio-codec = "0.1.0"

# [dependencies.hyper-fs]
# # git = "https://github.com/biluohc/hyper-fs"
# version = "0.1.1"
# default-features = false

[dependencies.systemstat]
version = "0.1.3"
# git = "https://github.com/myfreeweb/systemstat"
# branch = "master"

[dependencies.signalfn]
path = "./crates/signalfn"
version = "*"









